# Yaml Database for chest types

chest:
    type: task
    script:
    military:
        lvl:
            #This is the old setup for the database.
            #I want to change this one to the ones under the military set
            respawn: 10s-1m
            1:
            # item          thresh 
            #               | out_of 
            #               | | range 
            #               | | |   max_items
            - i@wood_sword  1 1 1-2 5
            - i@wood_axe    1 3 1   2
            - i@stone_sword 1 4 2   6
            - i@stone_axe   1 6 0-3 6
            
    residental:
        1:
            respawn: 10s-1m
            items:
            - i@bottle         1 10 1-2 5
            - i@cactus         1 20 1-3 6
            - i@leather_helmet 1 25 1   2
            - i@cake           1 10 2   2
            
    industrial:
        1:
            respawn: 10s-1m
            items:
            - i@wood_hoe 1 3 1 6
            - i@wood_axe 1 2 1 6
            - i@wood     1 4 1 100
    
    








